version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directories:
      - /
      - /apps/*
      - /packages/*
      - /infra
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - needs-triage
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - rust
      - needs-triage
    groups:
      cargo-minor-and-patch:
        update-types:
          - minor
          - patch
